apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "buncus.fullname" . }}
  labels:
    {{- include "buncus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "buncus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "buncus.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "buncus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: buncus
          image: {{ include "buncus.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          env:
            {{- include "buncus.env" . | nindent 12 }}
          {{- if eq (include "buncus.hasSecret" .) "true" }}
          envFrom:
            - secretRef:
                name: {{ include "buncus.secretName" . }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.tmpDir.enabled .Values.persistence.enabled }}
          volumeMounts:
            {{- if .Values.tmpDir.enabled }}
            - name: tmp
              mountPath: /tmp
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ dir (include "buncus.dbPath" .) }}
            {{- end }}
          {{- end }}
      {{- if or .Values.tmpDir.enabled .Values.persistence.enabled }}
      volumes:
        {{- if .Values.tmpDir.enabled }}
        - name: tmp
          emptyDir: {}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "buncus.fullname" .) }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
