{{- if eq (include "buncus.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buncus.fullname" . }}
  labels:
    {{- include "buncus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.githubAppId }}
  GITHUB_APP_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.githubClientId }}
  GITHUB_CLIENT_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.githubClientSecret }}
  GITHUB_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.githubPrivateKey }}
  GITHUB_PRIVATE_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.encryptionPassword }}
  ENCRYPTION_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.githubWebhookSecret }}
  GITHUB_WEBHOOK_SECRET: {{ . | quote }}
  {{- end }}
{{- end }}
